# https://probot.github.io/apps/settings/

# https://docs.github.com/en/rest/reference/repos#update-a-repository
repository:
  # A comma-separated list of topics to set on the repository
  topics: minecraft, modding, minecraft-modding

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

  # Either `true` to enable automatic deletion of branches on merge, or `false` to disable
  delete_branch_on_merge: true

  # Either `true` to enable automated security fixes, or `false` to disable
  # automated security fixes.
  enable_automated_security_fixes: true

  # Either `true` to enable vulnerability alerts, or `false` to disable
  # vulnerability alerts.
  enable_vulnerability_alerts: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: "prio: critical"
    color: "#B40813"
    description: ""

  - name: "prio: high"
    color: "#D7401D"
    description: ""

  - name: "prio: medium"
    color: "#FAC92F"
    description: ""

  - name: "prio: low"
    color: "#4AA751"
    description: ""

  - name: "state: awaiting response"
    color: "#E4E669"
    description: ""

  - name: "state: can't reproduce"
    color: "#CC6C66"
    description: ""

  - name: "state: completed"
    color: "#077713"
    description: ""

  - name: "state: confirmed"
    color: "#01CC80"
    description: ""

  - name: "state: denied"
    color: "#D53C4D"
    description: ""

  - name: "state: help wanted/needed"
    color: "#705DFB"
    description: ""

  - name: "state: in progress"
    color: "#FBCB07"
    description: ""

  - name: "state: pending"
    color: "#F61AB3"
    description: ""

  - name: "type: abandoned"
    color: "#CFD3D7"
    description: ""

  - name: "type: bug"
    color: "#D73A4A"
    description: ""

  - name: "type: duplicate"
    color: "#9C4D14"
    description: ""

  - name: "type: feature/enhancement"
    color: "#0075CA"
    description: ""

  - name: "type: invalid"
    color: "#CFD3D7"
    description: ""

  - name: "type: question"
    color: "#D876E3"
    description: ""

  - name: "type: support"
    color: "#C00B6A"
    description: ""
# See https://docs.github.com/en/rest/reference/teams#add-or-update-team-repository-permissions for available options
# teams:
#   - name: core
#     # The permission to grant the team. Can be one of:
#     # * `pull` - can pull, but not push to or administer this repository.
#     # * `push` - can pull and push, but not administer this repository.
#     # * `admin` - can pull, push and administer this repository.
#     # * `maintain` - Recommended for project managers who need to manage the repository without access to sensitive or destructive actions.
#     # * `triage` - Recommended for contributors who need to proactively manage issues and pull requests without write access.
#     permission: admin
#   - name: docs
#     permission: push
