blank_issues_enabled: false
contact_links:
  - name: Community Discord
    url: https://discord.com/invite/ThFnwZCyYY
    about: Join the Discord to get help and support!
  - name: Almost Reliable Organization
    url: https://github.com/AlmostReliable
    about: Check out our organization on GitHub!
