name: Setup Gradle

inputs:
  branch:
    description: branch that invoked the workflow
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: 17.0.8
        distribution: microsoft

    - uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: ${{ github.ref != format('{0}', inputs.branch) }}
        cache-overwrite-existing: true

    - shell: bash
      run: chmod +x ./gradlew
