name: Build

on:
  push:
    branches:
      - $default-branch
    tags-ignore:
      - '**'
    paths:
      - 'gradle/**'
      - '**.java'
      - '**.kts'
      - '**.properties'
      - '**/build.yml'
  pull_request:
    branches:
      - $default-branch
    paths:
      - 'gradle/**'
      - '**.java'
      - '**.kts'
      - '**.properties'
      - '**/build.yml'

jobs:
  redirect-workflow:
    uses: AlmostReliable/.github/.github/workflows/build-java17.yml@main
