name: Release

on:
  workflow_dispatch:
    inputs:
      target_version:
        type: string
        required: false
        description: "mod version | empty = next option"
      update_type:
        type: choice
        required: false
        description: "update type"
        default: "minor"
        options:
          - "major"
          - "minor"
          - "patch"
          - "none"
      release_type:
        type: choice
        required: true
        description: "type of release"
        default: "release"
        options:
          - "alpha"
          - "beta"
          - "release"
      debug:
        type: boolean
        required: false
        default: false
        description: "enable debug mode (GitHub only)"

env:
  MOD_NAME: "AlmostUnified" # name used for the output JAR files (use a dash instead of spaces)
  CURSEFORGE_ID: "633823" # ID of the project on CurseForge
  MODRINTH_ID: "sdaSaQEz" # ID of the project on Modrinth

jobs:
  redirect-workflow:
    uses: AlmostReliable/.github/.github/workflows/release-java17.yml@main
    secrets: inherit
    with:
      mod_name: ${{ env.MOD_NAME }}
      curseforge_id: ${{ env.CURSEFORGE_ID }}
      modrinth_id: ${{ env.MODRINTH_ID }}
      target_version: ${{ github.event.inputs.target_version }}
      update_type: ${{ github.event.inputs.update_type }}
      release_type: ${{ github.event.inputs.release_type }}
      loaders: fabric
      debug: ${{ github.event.inputs.debug }}
