name: Setup Gradle
description: "Setup Java and Gradle with configurable distribution and version."

inputs:
  java-distribution:
    description: java distribution to use
    required: false
    default: "microsoft"
  java-version:
    description: java version to use
    required: false
    default: "21"
  branch:
    description: branch that invoked the workflow
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}

    - uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: ${{ github.ref != format('{0}', inputs.branch) }}
        cache-overwrite-existing: true

    - shell: bash
      run: chmod +x ./gradlew

    - uses: gradle/wrapper-validation-action@v2
