name: Label Syncer

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/label-syncer.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
          repository: |
            AlmostReliable/almostlib
            AlmostReliable/almostpacked
            AlmostReliable/almostunified
            AlmostReliable/attributetooltipfix
            AlmostReliable/energymeter-forge
            AlmostReliable/kubejs-enderio
            AlmostReliable/lazierae2-forge
            AlmostReliable/lootjs
            AlmostReliable/merequester
            AlmostReliable/morejs
            AlmostReliable/ponderjs
            AlmostReliable/summoningrituals
          token: ${{ secrets.LABEL_SYNC_TOKEN }}
