name: Label Syncer

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/label-syncer.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    strategy:
      matrix:
        repos:
          - AlmostReliable/almostlib
          - AlmostReliable/almostpacked
          - AlmostReliable/almostunified
          - AlmostReliable/attributetooltipfix
          - AlmostReliable/energymeter-forge
          - AlmostReliable/kubejs-enderio
          - AlmostReliable/lazierae2-forge
          - AlmostReliable/lootjs
          - AlmostReliable/merequester
          - AlmostReliable/morejs
          - AlmostReliable/ponderjs
          - AlmostReliable/summoningrituals
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync labels
        uses: micnncim/action-label-syncer@v1.3.0
        with:
          repository: ${{ matrix.repos }}
          token: ${{ secrets.LABEL_SYNC_TOKEN }}
