name: Label Syncer

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/label-syncer.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Label Sync
        uses: srealmoreno/label-sync-action@v1
        with:
          token: ${{ secrets.LABEL_SYNC_TOKEN }}
          auto-discover-repos: true
          exclude-repos: |
            .github
          account-type: org
          exclude-forked-repos: true
          exclude-archived-repos: true
          exclude-private-repos: true
          exclude-disabled-repos: true
