name: "Support Request"

on:
  issues:
    types: [labeled, unlabeled, reopened]

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@v2
        with:
          github-token: ${{ github.token }}
          support-label: "type: support"
          issue-comment: |
            :wave: @{issue-author}!
            Please don't use the issue tracker for support requests.

            As stated in our [Contribution Guidelines](https://github.com/AlmostReliable/.github/blob/main/.github/CONTRIBUTING.md), we use it
            exclusively for bug reports and feature requests.

            Feel free to join our [Discord](https://discord.com/invite/ThFnwZCyYY) for help instead.
          close-issue: true
          lock-issue: false
          issue-lock-reason: "off-topic"
